version: '2.1'

services:

  dns: 
    image: coredns/coredns
    command: -conf coredns-config/Corefile
    ports:
      - 53:53/udp
    volumes:
      - ./config:/coredns-config/  

  traefik:
    image: traefik:latest
    command: >
      --web --docker --api
      --docker.domain=docker.local --docker.watch
      --accesslogsfile=/dev/stdout --logLevel=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    ports:
      - "80:80"
      - "8080:8080"    
    labels:
      - "traefik.port=8080"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.docker.local"

  httpbin:
    image: kennethreitz/httpbin
    labels:
      - "traefik.backend=httpbin"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:httpbin.docker.local"